[
  {
    "id" : "8f79428c-ab5c-4295-8849-fd2ad1faa508",
    "prId" : 1602,
    "prUrl" : "https://github.com/zio/zio/pull/1602#pullrequestreview-285251709",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "5bcb17c1-c3f6-45a0-b644-f44df5177a70",
        "parentId" : null,
        "authorId" : "fb116aef-1bf2-4605-9639-255437a2e564",
        "body" : "Maybe make this extend `TimeoutException`?",
        "createdAt" : "2019-09-09T00:27:10Z",
        "updatedAt" : "2019-09-09T00:27:10Z",
        "lastEditedBy" : "fb116aef-1bf2-4605-9639-255437a2e564",
        "tags" : [
        ]
      },
      {
        "id" : "b71c7b7e-628e-4a18-8bfa-f99aa3f73fc4",
        "parentId" : "5bcb17c1-c3f6-45a0-b644-f44df5177a70",
        "authorId" : "73db9f28-01ba-4a29-946b-7a2ae5ac5350",
        "body" : "It was the case initially but we changed for 2 reasons:\r\n- not generating any unnecessary call stack\r\n- since we don't display the full cause in `DefautTestReporter` for this error type, if a user uses `TimeoutException` in their code, they won't see the cause either. By using a separate class we can mute just that one.",
        "createdAt" : "2019-09-09T00:29:22Z",
        "updatedAt" : "2019-09-09T00:29:22Z",
        "lastEditedBy" : "73db9f28-01ba-4a29-946b-7a2ae5ac5350",
        "tags" : [
        ]
      },
      {
        "id" : "aaf5f0ed-1be7-4e20-acff-526ee882c95f",
        "parentId" : "5bcb17c1-c3f6-45a0-b644-f44df5177a70",
        "authorId" : "e51a12a9-b5b7-4e30-a51d-293206825c6f",
        "body" : "If we made `TestTimeoutException` extend `TimeoutException` and pattern matched on `TestTimeoutException` in `DefaultTestReporter` wouldn't that still get us what we want? Or do we lose the ability to specify no stack trace if we do that?",
        "createdAt" : "2019-09-09T01:42:11Z",
        "updatedAt" : "2019-09-09T01:42:12Z",
        "lastEditedBy" : "e51a12a9-b5b7-4e30-a51d-293206825c6f",
        "tags" : [
        ]
      },
      {
        "id" : "1f1854d4-483d-4338-97e5-0bad98fb0c84",
        "parentId" : "5bcb17c1-c3f6-45a0-b644-f44df5177a70",
        "authorId" : "73db9f28-01ba-4a29-946b-7a2ae5ac5350",
        "body" : "I think it would generate a stack trace then. But what would be the benefit?",
        "createdAt" : "2019-09-09T01:44:00Z",
        "updatedAt" : "2019-09-09T01:44:00Z",
        "lastEditedBy" : "73db9f28-01ba-4a29-946b-7a2ae5ac5350",
        "tags" : [
        ]
      },
      {
        "id" : "e886c5ae-b593-4c01-a8e0-fd8f1d834a1a",
        "parentId" : "5bcb17c1-c3f6-45a0-b644-f44df5177a70",
        "authorId" : "e51a12a9-b5b7-4e30-a51d-293206825c6f",
        "body" : "Yeah, I thought it might just be good for consistency if we ever want to do anything else with to handle that exception, but we will always know what it is. I'm good to merge.",
        "createdAt" : "2019-09-09T01:45:31Z",
        "updatedAt" : "2019-09-09T01:45:32Z",
        "lastEditedBy" : "e51a12a9-b5b7-4e30-a51d-293206825c6f",
        "tags" : [
        ]
      }
    ],
    "commit" : "d939e57545399c7ac467bf93434e3ef93223fd2b",
    "line" : 19,
    "diffHunk" : "@@ -1,1 +17,21 @@package zio.test\n\nfinal case class TestTimeoutException(message: String) extends Throwable(message, null, true, false)"
  }
]