[
  {
    "id" : "f8272c8d-ed7c-49eb-97eb-fc623bc9bfa6",
    "prId" : 4683,
    "prUrl" : "https://github.com/root-project/root/pull/4683#pullrequestreview-330834590",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "a8c2268f-ffec-4ded-8225-9d57b7229086",
        "parentId" : null,
        "authorId" : "335eabbd-4b70-43fb-a046-bf82995f5dd3",
        "body" : "For 'fun' shouldn't we also add an assignment in the catch close to check it is run?",
        "createdAt" : "2019-12-11T20:52:12Z",
        "updatedAt" : "2020-04-30T13:05:23Z",
        "lastEditedBy" : "335eabbd-4b70-43fb-a046-bf82995f5dd3",
        "tags" : [
        ]
      }
    ],
    "commit" : "c0bfcd5b0a8574ba1013a306efd101ad3f5ebd33",
    "line" : 68,
    "diffHunk" : "@@ -1,1 +66,70 @@      EXPECT_THAT(e.GetError().GetStackTrace().at(0).fFunction, ::testing::HasSubstr(\"TestSyscall(bool)\"));\n      EXPECT_THAT(e.GetError().GetStackTrace().at(1).fFunction, ::testing::HasSubstr(\"TestChain(bool)\"));\n   }\n}\n"
  }
]