[
  {
    "id" : "fdbc55c0-fbea-48b3-9c7f-186c486ceb6e",
    "prId" : 33769,
    "prUrl" : "https://github.com/ansible/ansible/pull/33769#pullrequestreview-115800907",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "1998e546-bf69-4442-b8c8-97b0907dd9f5",
        "parentId" : null,
        "authorId" : "8e448afa-36a6-4325-b7c1-0522cb01977c",
        "body" : "@s-hertel i'm not sure this works here.  If the ELB doesn't exist then the retry logic means it'll keep retrying causing a large delay even though it's quite likely we just want to move on and create the ELB.",
        "createdAt" : "2018-04-21T04:03:05Z",
        "updatedAt" : "2018-05-04T18:37:17Z",
        "lastEditedBy" : "8e448afa-36a6-4325-b7c1-0522cb01977c",
        "tags" : [
        ]
      },
      {
        "id" : "055ed6c5-0780-4b22-97b2-680d05e7f20d",
        "parentId" : "1998e546-bf69-4442-b8c8-97b0907dd9f5",
        "authorId" : "6b7e4265-ae86-4269-9bd7-f8ffa9085df6",
        "body" : "@wimnat I think this is right. It should return None without retrying at all if the Load Balancer doesn't exist. It will just retry for exceptions that aren't handled. I'm checking this with a concrete example now though.\r\n\r\nYes. I turned on the timer callback and used this playbook:\r\n```\r\n---\r\n- hosts: localhost\r\n  connection: local\r\n  gather_facts: no\r\n  tasks:\r\n    - name: create a new application lb\r\n      elb_application_lb:\r\n        profile: shertel\r\n        region: ca-central-1\r\n        name: \"{{ lb_name }}\"\r\n        security_groups:\r\n          - \"{{ sg_1 }}\"\r\n        subnets:\r\n          - \"{{ subnet_1 }}\"\r\n          - \"{{ subnet_2 }}\"\r\n        state: present\r\n\r\n    - name: clean up\r\n      elb_application_lb:\r\n        profile: shertel\r\n        region: ca-central-1\r\n        name: \"{{ lb_name }}\"\r\n        state: absent\r\n```\r\nThese tasks take 2 seconds for me on devel and on this branch.\r\n`Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds`",
        "createdAt" : "2018-04-23T13:22:14Z",
        "updatedAt" : "2018-05-04T18:37:17Z",
        "lastEditedBy" : "6b7e4265-ae86-4269-9bd7-f8ffa9085df6",
        "tags" : [
        ]
      },
      {
        "id" : "de906804-eb03-4545-bcd4-cff557f9bc3d",
        "parentId" : "1998e546-bf69-4442-b8c8-97b0907dd9f5",
        "authorId" : "6b7e4265-ae86-4269-9bd7-f8ffa9085df6",
        "body" : "If I remove the `return None` and raise the exception again instead it does retry (before failing since the `return None` is necessary): `Playbook run took 0 days, 0 hours, 4 minutes, 33 seconds`",
        "createdAt" : "2018-04-23T13:48:53Z",
        "updatedAt" : "2018-05-04T18:37:17Z",
        "lastEditedBy" : "6b7e4265-ae86-4269-9bd7-f8ffa9085df6",
        "tags" : [
        ]
      },
      {
        "id" : "166e6262-7809-4fbb-b41c-b730dd8f393c",
        "parentId" : "1998e546-bf69-4442-b8c8-97b0907dd9f5",
        "authorId" : "8e448afa-36a6-4325-b7c1-0522cb01977c",
        "body" : "Hmm I had different behaviour over the weekend. Let me retry and get back to you",
        "createdAt" : "2018-04-24T10:30:00Z",
        "updatedAt" : "2018-05-04T18:37:17Z",
        "lastEditedBy" : "8e448afa-36a6-4325-b7c1-0522cb01977c",
        "tags" : [
        ]
      },
      {
        "id" : "9b588d8d-2a1c-4341-ae87-8043f25cdffa",
        "parentId" : "1998e546-bf69-4442-b8c8-97b0907dd9f5",
        "authorId" : "8e448afa-36a6-4325-b7c1-0522cb01977c",
        "body" : "Can not replicate behaviour so let's sweep this under the carpet ;)",
        "createdAt" : "2018-04-27T01:55:05Z",
        "updatedAt" : "2018-05-04T18:37:17Z",
        "lastEditedBy" : "8e448afa-36a6-4325-b7c1-0522cb01977c",
        "tags" : [
        ]
      }
    ],
    "commit" : "6629ea73a52645d5461c87e91a0538146aabb85e",
    "line" : 29,
    "diffHunk" : "@@ -1,1 +27,31 @@\n\n@AWSRetry.jittered_backoff()\ndef _get_elb(connection, module, elb_name):\n    \"\"\""
  }
]