[
  {
    "id" : "305c3fde-f06a-40c8-b848-0f318cbf3735",
    "prId" : 6808,
    "prUrl" : "https://github.com/apache/kafka/pull/6808#pullrequestreview-241822662",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "b9e2882e-47bd-4396-9d7d-be9a3d14f32a",
        "parentId" : null,
        "authorId" : "9baadc38-cd41-4762-be0c-791258ced78c",
        "body" : "Can we add those test for `MeteredTimestampedKeyValueStoreTest`, too. We had the same bug in `MeteredTimestampedKeyValueStore` and fixed it \"on the side\" but never added a test...",
        "createdAt" : "2019-05-24T15:44:40Z",
        "updatedAt" : "2019-05-24T16:44:10Z",
        "lastEditedBy" : "9baadc38-cd41-4762-be0c-791258ced78c",
        "tags" : [
        ]
      },
      {
        "id" : "5b22a205-eb94-44e9-8a58-0ed73eb02a85",
        "parentId" : "b9e2882e-47bd-4396-9d7d-be9a3d14f32a",
        "authorId" : "b7cbfdaf-f3e2-4130-8254-501ace9562ac",
        "body" : "Will open a separate PR for that.",
        "createdAt" : "2019-05-24T15:58:54Z",
        "updatedAt" : "2019-05-24T16:44:10Z",
        "lastEditedBy" : "b7cbfdaf-f3e2-4130-8254-501ace9562ac",
        "tags" : [
        ]
      }
    ],
    "commit" : "05012465210d4f40f47f035c8f67324c42f71fdf",
    "line" : 23,
    "diffHunk" : "@@ -1,1 +94,98 @@\n    @Test\n    public void shouldNotThrowExceptionIfSerdesCorrectlySetFromProcessorContext() {\n        EasyMock.expect(innerStoreMock.name()).andStubReturn(\"mocked-store\");\n        EasyMock.replay(innerStoreMock);"
  },
  {
    "id" : "36fd70ee-8ef6-42ac-be6f-58f07b8e199d",
    "prId" : 6808,
    "prUrl" : "https://github.com/apache/kafka/pull/6808#pullrequestreview-241822662",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "f779ba96-b567-48c0-b1f0-11a9db70f0a0",
        "parentId" : null,
        "authorId" : "9baadc38-cd41-4762-be0c-791258ced78c",
        "body" : "I don't understand this ? Why do we catch `StreamsException`? Should the test not just fail if an exception is thrown?",
        "createdAt" : "2019-05-24T15:46:44Z",
        "updatedAt" : "2019-05-24T16:44:10Z",
        "lastEditedBy" : "9baadc38-cd41-4762-be0c-791258ced78c",
        "tags" : [
        ]
      },
      {
        "id" : "ac39de9b-63f7-43d1-b3ad-f209bae15ad6",
        "parentId" : "f779ba96-b567-48c0-b1f0-11a9db70f0a0",
        "authorId" : "b7cbfdaf-f3e2-4130-8254-501ace9562ac",
        "body" : "To distinguish between a test failure and a test that is terminated by an exception. If a `StreamsException` that  caused by a `ClassCastException` was thrown by `store.put()`, then the test failed because the behaviour under test was not correct, otherwise it was terminated due to some other issues.",
        "createdAt" : "2019-05-24T15:58:27Z",
        "updatedAt" : "2019-05-24T16:44:10Z",
        "lastEditedBy" : "b7cbfdaf-f3e2-4130-8254-501ace9562ac",
        "tags" : [
        ]
      }
    ],
    "commit" : "05012465210d4f40f47f035c8f67324c42f71fdf",
    "line" : 38,
    "diffHunk" : "@@ -1,1 +109,113 @@        try {\n            store.put(\"key\", ValueAndTimestamp.make(42L, 60000));\n        } catch (final StreamsException exception) {\n            if (exception.getCause() instanceof ClassCastException) {\n                fail(\"Serdes are not correctly set from processor context.\");"
  },
  {
    "id" : "bea9a13a-ab53-424b-810b-670cc0bc8d3b",
    "prId" : 6808,
    "prUrl" : "https://github.com/apache/kafka/pull/6808#pullrequestreview-241815718",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "da1f0d7f-5b8b-4c3d-85e5-d35240260444",
        "parentId" : null,
        "authorId" : "9baadc38-cd41-4762-be0c-791258ced78c",
        "body" : "As above",
        "createdAt" : "2019-05-24T15:49:27Z",
        "updatedAt" : "2019-05-24T16:44:10Z",
        "lastEditedBy" : "9baadc38-cd41-4762-be0c-791258ced78c",
        "tags" : [
        ]
      }
    ],
    "commit" : "05012465210d4f40f47f035c8f67324c42f71fdf",
    "line" : 62,
    "diffHunk" : "@@ -1,1 +133,137 @@        try {\n            store.put(\"key\", ValueAndTimestamp.make(42L, 60000));\n        } catch (final StreamsException exception) {\n            if (exception.getCause() instanceof ClassCastException) {\n                fail(\"Serdes are not correctly set from constructor parameters.\");"
  },
  {
    "id" : "a6f53a63-b32f-4a71-99a3-9f5f1ac38beb",
    "prId" : 6808,
    "prUrl" : "https://github.com/apache/kafka/pull/6808#pullrequestreview-242153833",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "c5391e93-62df-41c7-9d4d-502f89448528",
        "parentId" : null,
        "authorId" : "4c968502-bb3d-46ee-8719-0c0bdbc6242f",
        "body" : "nit: IMHO we should just get rid of the `try/catch` as if the cause is anything other than a `ClassCastException`  this test will still pass. ",
        "createdAt" : "2019-05-24T15:57:11Z",
        "updatedAt" : "2019-05-24T16:44:10Z",
        "lastEditedBy" : "4c968502-bb3d-46ee-8719-0c0bdbc6242f",
        "tags" : [
        ]
      },
      {
        "id" : "35378fad-078f-4a55-855f-e82794165ac2",
        "parentId" : "c5391e93-62df-41c7-9d4d-502f89448528",
        "authorId" : "b7cbfdaf-f3e2-4130-8254-501ace9562ac",
        "body" : "I will add an `else` branch and re-throw the exception. That will still distinguish between a failed and a terminated test as explained above.",
        "createdAt" : "2019-05-24T16:06:37Z",
        "updatedAt" : "2019-05-24T16:44:10Z",
        "lastEditedBy" : "b7cbfdaf-f3e2-4130-8254-501ace9562ac",
        "tags" : [
        ]
      },
      {
        "id" : "cf0ad3c8-6227-452c-a61a-bb06edd62a1e",
        "parentId" : "c5391e93-62df-41c7-9d4d-502f89448528",
        "authorId" : "9baadc38-cd41-4762-be0c-791258ced78c",
        "body" : "I agree with @bbejeck (compare my other comment about \"why we catch `StreamsException`) -- if any exception is thrown, the test should fail. We don't gain anything IMHO by calling `fail` vs re-throwing -- it's just confusing the read the test.",
        "createdAt" : "2019-05-24T18:37:20Z",
        "updatedAt" : "2019-05-24T18:37:21Z",
        "lastEditedBy" : "9baadc38-cd41-4762-be0c-791258ced78c",
        "tags" : [
        ]
      },
      {
        "id" : "c4ddb96f-3abe-47c8-8811-3ef08123c357",
        "parentId" : "c5391e93-62df-41c7-9d4d-502f89448528",
        "authorId" : "b7cbfdaf-f3e2-4130-8254-501ace9562ac",
        "body" : "OK, I see that the tests fail in any case when an exception is thrown. However, I still think that catching `StreamException` and checking if `ClassCastException` is its cause is a good idea to document what this test is verifying. Without the `try-catch` it is just a couple of lines of code without any assert, which may be puzzling when read in a couple of month. Additionally, the distinction between misbehaviour of code under test (i.e. test fails with predefined message in test) and other issue (some exception was thrown) seems still relevant to me for debugging.\r\n\r\nIf you both still do not agree, I will remove the `try-catch` clause for the sake of getting this bugfix in.",
        "createdAt" : "2019-05-27T08:24:18Z",
        "updatedAt" : "2019-05-27T08:24:18Z",
        "lastEditedBy" : "b7cbfdaf-f3e2-4130-8254-501ace9562ac",
        "tags" : [
        ]
      }
    ],
    "commit" : "05012465210d4f40f47f035c8f67324c42f71fdf",
    "line" : 39,
    "diffHunk" : "@@ -1,1 +110,114 @@            store.put(\"key\", ValueAndTimestamp.make(42L, 60000));\n        } catch (final StreamsException exception) {\n            if (exception.getCause() instanceof ClassCastException) {\n                fail(\"Serdes are not correctly set from processor context.\");\n            }"
  },
  {
    "id" : "33ed353a-4767-4f26-b156-20108dccd84a",
    "prId" : 6808,
    "prUrl" : "https://github.com/apache/kafka/pull/6808#pullrequestreview-241821988",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "538dc956-bd11-43a5-acbd-a444c998c550",
        "parentId" : null,
        "authorId" : "4c968502-bb3d-46ee-8719-0c0bdbc6242f",
        "body" : "same as above",
        "createdAt" : "2019-05-24T15:57:23Z",
        "updatedAt" : "2019-05-24T16:44:10Z",
        "lastEditedBy" : "4c968502-bb3d-46ee-8719-0c0bdbc6242f",
        "tags" : [
        ]
      }
    ],
    "commit" : "05012465210d4f40f47f035c8f67324c42f71fdf",
    "line" : 63,
    "diffHunk" : "@@ -1,1 +134,138 @@            store.put(\"key\", ValueAndTimestamp.make(42L, 60000));\n        } catch (final StreamsException exception) {\n            if (exception.getCause() instanceof ClassCastException) {\n                fail(\"Serdes are not correctly set from constructor parameters.\");\n            }"
  }
]