[
  {
    "id" : "d59ca3ae-10dd-4719-94f6-e59cc57b80df",
    "prId" : 35100,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/35100#pullrequestreview-443472215",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "8ba50843-0490-45c5-92b9-34d0fb9f521d",
        "parentId" : null,
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "what if i want to just run the test suite? (e.g. in the case of #35077 the tests that segfault only do so if run in the whole test suite, not something ive been able to replicate in the REPL)",
        "createdAt" : "2020-07-06T21:46:29Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      },
      {
        "id" : "84585c8d-9cd8-4853-ad1f-78d8b71ef008",
        "parentId" : "8ba50843-0490-45c5-92b9-34d0fb9f521d",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "Does `run pytest` work?",
        "createdAt" : "2020-07-06T21:47:26Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      },
      {
        "id" : "1d04a94d-3ee5-4ee3-81b7-6a2f0de034af",
        "parentId" : "8ba50843-0490-45c5-92b9-34d0fb9f521d",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "Or you can try `gdb --args python -m pytest ...` / `lldb -- python -m pytest ...` and then type `run` in the interactive session. the latter is working for me on my Mac\r\n\r\nI don't totally understand how the whole launching / run machinery works just yet so there's probably another way to do it interactively",
        "createdAt" : "2020-07-06T23:23:19Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      },
      {
        "id" : "eb49427b-e1c3-4059-9297-02e3032d981d",
        "parentId" : "8ba50843-0490-45c5-92b9-34d0fb9f521d",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "Appended some info for this which should help",
        "createdAt" : "2020-07-06T23:42:05Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      }
    ],
    "commit" : "3b8de2e4a686abcf553498bd51fc5176d292c382",
    "line" : 62,
    "diffHunk" : "@@ -1,1 +60,64 @@.. code-block:: sh\n\n   run <the_script>.py\n\nCode execution will halt at the breakpoint defined or at the occurance of any segfault. LLDB's `GDB to LLDB command map <https://lldb.llvm.org/use/map.html>`_ provides a listing of debugger command that you can execute using either debugger."
  },
  {
    "id" : "788b70cf-01fb-43b0-ba75-6a437ad9e430",
    "prId" : 35100,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/35100#pullrequestreview-488120381",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "parentId" : null,
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "\r\n```\r\n$ gdb --args python3 -m pytest\r\n[...]\r\n\"~/.pyenv/shims/python3\": not in executable format: File format not recognized\r\n(gdb) run\r\nStarting program:  -m pytest\r\nNo executable file specified.\r\nUse the \"file\" or \"exec-file\" command.\r\n```",
        "createdAt" : "2020-07-07T01:49:33Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      },
      {
        "id" : "0256d1d8-2ea4-4ac8-b89c-11b2adc7027f",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "Can you try `gdb -ex r --args python3 -m pytest`? Taking that from this link:\r\n\r\nhttps://wiki.python.org/moin/DebuggingWithGdb",
        "createdAt" : "2020-07-07T02:39:58Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      },
      {
        "id" : "9b6b9221-2977-4a85-9978-fe72dc27d26d",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "Yea looks like `gdb -ex r --args python3 -m pytest pandas/tests` was working for me if you want to try on yours and confirm",
        "createdAt" : "2020-07-07T16:03:49Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      },
      {
        "id" : "d9bcc4c8-bc86-471e-94e5-d81abfccd858",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "```\r\n$ gdb -ex r --args python3 -m pytest pandas/tests\r\n[...]\r\n\"~/.pyenv/shims/python3\": not in executable format: File format not recognized\r\nStarting program:  -m pytest pandas/tests\r\nNo executable file specified.\r\nUse the \"file\" or \"exec-file\" command.\r\n(gdb) \r\n```",
        "createdAt" : "2020-07-07T17:12:50Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      },
      {
        "id" : "0eee4188-e901-49b5-a472-d3b1274effd3",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "Are you using pyenv for development or Conda?",
        "createdAt" : "2020-07-07T17:14:15Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      },
      {
        "id" : "a32e335b-9fd1-4c44-8ca9-9ba805c3367a",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "pyenv",
        "createdAt" : "2020-07-07T17:15:01Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      },
      {
        "id" : "b61e5ea9-92e3-4381-813e-27d8e263cc51",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "you've already gone above and beyond helping me debug this; ill spend some more time on this and ping you if i find anything new",
        "createdAt" : "2020-07-07T17:15:59Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      },
      {
        "id" : "7b81b6a7-49fe-49fd-8064-d65a0294a71c",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "All good - I think this is generally helpful to hash out together so thanks for the input.\r\n\r\nIt looks like this might be specific to pyenv and how it manages the python executable:\r\n\r\nhttps://stackoverflow.com/questions/48141135/cannot-start-dbg-on-my-python-c-extension\r\n\r\n",
        "createdAt" : "2020-07-07T17:17:12Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      },
      {
        "id" : "7f47f713-2caa-4692-95d6-7f753a84c13c",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "`gdb -ex r --args bash pytest pandas/tests --skip-slow --skip-db` tentatively looks like a winner",
        "createdAt" : "2020-07-07T17:26:26Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      },
      {
        "id" : "9de31fe5-c7a8-4df8-9c33-ef4006c56545",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "is the command from my previous comment specific to my case, or relevant to the document?",
        "createdAt" : "2020-09-11T01:09:21Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      },
      {
        "id" : "b3e9d85d-5827-485e-bb77-ab5445e3d657",
        "parentId" : "3ac10a0b-d494-4da1-8a7f-c361f9d205b9",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "I'm trying to avoid adding too much detail here since this issue is more of a pyenv thing than a debugger issue",
        "createdAt" : "2020-09-14T20:34:18Z",
        "updatedAt" : "2020-12-09T00:49:33Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      }
    ],
    "commit" : "3b8de2e4a686abcf553498bd51fc5176d292c382",
    "line" : 76,
    "diffHunk" : "@@ -1,1 +74,78 @@.. code-block:: sh\n\n   gdb --args python -m pytest\n\nOnce the process launches, simply type ``run`` and the test suite will begin, stopping at any segmentation fault that may occur."
  }
]