[
  {
    "id" : "d63e6503-3af1-48c5-8b90-829228ed45e0",
    "prId" : 2469,
    "prUrl" : "https://github.com/conda-forge/staged-recipes/pull/2469#pullrequestreview-23168708",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "897bf8cb-ea32-49d8-922b-bc31dd6a0576",
        "parentId" : null,
        "authorId" : "085a9c6b-569e-49bd-9434-7f128372cf0c",
        "body" : "Strangely, the `__version__` in the package from pypi.io says 3.5.0 (although the tarball is labeled as 3.6.0)",
        "createdAt" : "2017-02-20T20:03:21Z",
        "updatedAt" : "2017-02-21T09:51:55Z",
        "lastEditedBy" : "085a9c6b-569e-49bd-9434-7f128372cf0c",
        "tags" : [
        ]
      },
      {
        "id" : "f5eaf1a6-5dda-4a12-9798-f5d4d29a0c12",
        "parentId" : "897bf8cb-ea32-49d8-922b-bc31dd6a0576",
        "authorId" : "a9d266d1-93e6-4b46-b68c-efe7d71e41f4",
        "body" : "set `setup.py` has the correct version \"3.6.0\". The `__version__` was not adapted ... but i have looked in the github code and it was fixed after the 3.6.0 release:\r\n\r\nhttps://github.com/django-haystack/pysolr/blob/master/pysolr.py#L61",
        "createdAt" : "2017-02-22T09:24:33Z",
        "updatedAt" : "2017-02-22T09:24:33Z",
        "lastEditedBy" : "a9d266d1-93e6-4b46-b68c-efe7d71e41f4",
        "tags" : [
        ]
      }
    ],
    "commit" : "baac0b55ac706f6357fc10e4ca9c4303022d0331",
    "line" : 2,
    "diffHunk" : "@@ -1,1 +0,4 @@{% set name = \"pysolr\" %}\n{% set version = \"3.6.0\" %}\n\npackage:"
  }
]