[
  {
    "id" : "ba446142-6861-4122-b3ad-0463e48ac9fe",
    "prId" : 81163,
    "prUrl" : "https://github.com/kubernetes/kubernetes/pull/81163#pullrequestreview-274205350",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "4c19933a-c322-4c35-922e-ce50f5bca2e5",
        "parentId" : null,
        "authorId" : "241ab19e-f85a-4d22-92e2-88f2b6287d14",
        "body" : "where does the error come from, is it a timeout or won't `expectedVolumes` have len 0?",
        "createdAt" : "2019-08-12T18:02:47Z",
        "updatedAt" : "2019-08-15T09:07:31Z",
        "lastEditedBy" : "241ab19e-f85a-4d22-92e2-88f2b6287d14",
        "tags" : [
        ]
      },
      {
        "id" : "16ad5162-c14d-405b-9abc-acd407c007cd",
        "parentId" : "4c19933a-c322-4c35-922e-ce50f5bca2e5",
        "authorId" : "8b64e744-955d-4523-a3b7-60fae9df0857",
        "body" : "It's not timeout, DSWP has stored error into DSW and `WaitForAttachAndMount` asynchronously picked it up within ~`podAttachAndMountRetryInterval` (300ms)",
        "createdAt" : "2019-08-13T10:59:38Z",
        "updatedAt" : "2019-08-15T09:07:31Z",
        "lastEditedBy" : "8b64e744-955d-4523-a3b7-60fae9df0857",
        "tags" : [
        ]
      }
    ],
    "commit" : "2c79ffe274c3bb5a2dad38cde866425018033e10",
    "line" : 85,
    "diffHunk" : "@@ -1,1 +89,93 @@\t\t\tpodMode:     v1.PersistentVolumeFilesystem,\n\t\t\texpectMount: false,\n\t\t\texpectError: true,\n\t\t},\n\t}"
  },
  {
    "id" : "2f8d7d2a-52e3-4989-914c-31cea6ff1cce",
    "prId" : 80369,
    "prUrl" : "https://github.com/kubernetes/kubernetes/pull/80369#pullrequestreview-267836718",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "7b50f9f4-d226-4de1-8773-ab48d11b6078",
        "parentId" : null,
        "authorId" : "44594ff0-8fbc-44a7-84f9-654ffd54270f",
        "body" : "without this wait.Poll, the test should be flaky? ",
        "createdAt" : "2019-07-26T21:05:40Z",
        "updatedAt" : "2019-08-05T08:08:51Z",
        "lastEditedBy" : "44594ff0-8fbc-44a7-84f9-654ffd54270f",
        "tags" : [
        ]
      },
      {
        "id" : "8ccf93ae-5fb5-4a00-8556-e4365960514d",
        "parentId" : "7b50f9f4-d226-4de1-8773-ab48d11b6078",
        "authorId" : "8b64e744-955d-4523-a3b7-60fae9df0857",
        "body" : "Yes, because the PVC is bound after a short delay (see above) and the first few calls return error that the PVC is not bound yet. ",
        "createdAt" : "2019-07-29T14:49:35Z",
        "updatedAt" : "2019-08-05T08:08:51Z",
        "lastEditedBy" : "8b64e744-955d-4523-a3b7-60fae9df0857",
        "tags" : [
        ]
      }
    ],
    "commit" : "c744385804a7e51fdb15cc86894b30ff69bdcd70",
    "line" : 17,
    "diffHunk" : "@@ -1,1 +126,130 @@\tgo delayClaimBecomesBound(kubeClient, claim.GetNamespace(), claim.ObjectMeta.Name)\n\n\terr = wait.Poll(100*time.Millisecond, 1*time.Second, func() (bool, error) {\n\t\terr = manager.WaitForAttachAndMount(pod)\n\t\tif err != nil {"
  },
  {
    "id" : "5957c000-8b3f-4f0e-8a52-e97ceeb5dbdd",
    "prId" : 29119,
    "prUrl" : null,
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "b1f58cb2-18c8-425a-aa11-d2acaa36df50",
        "parentId" : null,
        "authorId" : "498aade9-b8f0-4e29-8055-89afa6f5fcc8",
        "body" : "you should do a `continue` here -- otherwise you'll just get an extra failure\n",
        "createdAt" : "2016-07-22T20:29:31Z",
        "updatedAt" : "2016-07-22T21:44:37Z",
        "lastEditedBy" : "498aade9-b8f0-4e29-8055-89afa6f5fcc8",
        "tags" : [
        ]
      }
    ],
    "commit" : "ae1575b5cc8e697c69a911720caaf22bdacca3c1",
    "line" : 165,
    "diffHunk" : "@@ -1,1 +163,167 @@\t\terr = manager.WaitForAttachAndMount(pod)\n\t\tif err != nil {\n\t\t\tt.Errorf(\"Expected success: %v\", err)\n\t\t\tcontinue\n\t\t}"
  }
]