[
  {
    "id" : "7e9cf010-a071-4d97-8130-458462682054",
    "prId" : 59165,
    "prUrl" : "https://github.com/kubernetes/kubernetes/pull/59165#pullrequestreview-94210407",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "7a75f977-519c-46bb-bf29-da208ea73ff3",
        "parentId" : null,
        "authorId" : "21b457d2-6f88-4a9f-8d5a-debafbcb6cfe",
        "body" : "This condition is always false because all use-cases have `expectErr: false`. In fact this branch and `expectErr`/`expectedError` members can be safely removed from this test as they aren't used at all.",
        "createdAt" : "2018-02-05T15:15:37Z",
        "updatedAt" : "2018-02-06T03:01:24Z",
        "lastEditedBy" : "21b457d2-6f88-4a9f-8d5a-debafbcb6cfe",
        "tags" : [
        ]
      },
      {
        "id" : "b6c93b87-02fe-47ac-b248-cb3005e1f26d",
        "parentId" : "7a75f977-519c-46bb-bf29-da208ea73ff3",
        "authorId" : "d0e97b49-eba2-4b22-8695-df4f8a6776ad",
        "body" : "Ah, thanks for pointing that out, I missed the error case. I added a test for the error case, and removed `expectErr` from all of the other test cases for clarity...",
        "createdAt" : "2018-02-06T02:34:52Z",
        "updatedAt" : "2018-02-06T03:01:24Z",
        "lastEditedBy" : "d0e97b49-eba2-4b22-8695-df4f8a6776ad",
        "tags" : [
        ]
      }
    ],
    "commit" : "d6bb43473037f3eb6a1bca698430c0fd2c7697c9",
    "line" : 151,
    "diffHunk" : "@@ -1,1 +149,153 @@\tfor _, test := range tests {\n\t\troutes, err := processRoutes(test.rt, test.exists, test.err)\n\t\tif test.expectErr {\n\t\t\tif err == nil {\n\t\t\t\tt.Errorf(\"%s: unexpected non-error\", test.name)"
  }
]